### ISSUE TITLE
refactor: change UI of the left container

### ISSUE THREAD

**Issue by 2o1da** [42Box/macOS#85]
macOS 창의 왼쪽 상단에 빨간색, 노란색, 초록색 버튼을 뜨게 하려면 기존의 NSPopover가 아닌 NSWindow를 사용해야합니다.

현재 NSWindow의 타이틀바의 경계선이 생기는데 이를 없애는데 어려움을 겪고 있습니다.

**Comment by 2o1da** [comment]
NSWindow의 왼쪽 상단에 빨간색, 노란색, 초록색 버튼의 색상을 커스텀하는 것은 불가능할 것으로 보입니다.

> 애플의 사용자 인터페이스 가이드라인에서는 이러한 컨트롤에 대한 사용자 경험을 일관되게 유지하기 위해 이들을 변경하지 말 것을 권장하고 있습니다. 따라서, 이런 변경을 시도하면 사용자가 기대하는 macOS의 일반적인 동작을 방해하게 될 수 있습니다.
또한, 이러한 접근은 App Store 심사 지침에 위반될 수 있으며 앱이 거부될 수 있습니다.

**Comment by chanhihi** [comment]
커스텀버튼으로 해결하였습니다 
- #80 
- #81
